var number = [2, 3, 4, 5, 6];
number.push(8);
console.log(number);
var fruit = ["mango", "banana", "apple"];
fruit.push("litchi");
console.log(fruit);
var color = ['red', 'yellow', 'blue'];
console.log(color);
var mixed = ['cat', 67, 'mat', 65];
console.log(mixed);
